### ISSUE TITLE
Published versions of this package don't seem to include the latest changes

### ISSUE THREAD

**Issue by rocketraman** [ancashoria/graphql-kafka-subscriptions#14]
Looking at the commit history of this package, I see for example commit ba8da4f, and then commits to create versions 0.2.5 and 0.2.6. Neither of the latter versions on npm seem to include the code for ba8da4f.

Are you perhaps missing a `yarn build` step in your publishing steps?

**Comment by ancashoria** [comment]
Hi @rocketraman 
I just tested this by doing an npm install and checking the node_modules folder and here's the code in question:
```
KafkaPubSub.prototype.brokerList = function () {
    return this.options.host.match(',') ? this.options.host : this.options.host + ":" + this.options.port;
};
```

**Comment by rocketraman** [comment]
@ancashoria Exactly my point -- that code is not the latest code.

**Comment by rocketraman** [comment]
Here is the latest code:

https://github.com/ancashoria/graphql-kafka-subscriptions/blob/master/src/kafka-pubsub.ts#L85-L87

**Comment by sjsyrek** [comment]
I would like to bump @rocketraman's comment :)

**Comment by rodrigopinto** [comment]
We will be releasing a new version soon. @fmannhardt made some improvements on #24 and it is currently merged to the deve branch. We'll improve the documentation as well and get a new version asap. Please bear with me!

**Comment by fmannhardt** [comment]
I just need to find 1-2 hrs to wraps this up :-)

**Comment by dfrancoultra** [comment]
I don't want to bother, but do we have an ETA for this?

**Comment by rodrigopinto** [comment]
Hi @rocketraman and @dfrancoultra, we just release a 0.4.0 version with the most recent changes merge to master.
Please try it and let us know in case you find something.

**Comment by fmannhardt** [comment]
Thanks a lot for taking charge of finally integrating this. I had no time at all for open source stuff the the past months.
