### ISSUE TITLE
Does not work after a few messages.

### ISSUE THREAD

**Issue by wzahedi** [ancashoria/graphql-kafka-subscriptions#25]
Hi, I followed the usage guide and it works for a few messages at first, and then after maybe 4/5 payloads, it does not deliver to clients. I started a separate Kafka console consumer, and I am still able to receive messages despite this, which leads me to believe the issue is with the async iterator? Need to understand how to fix this otherwise this library won't be usable unfortunately. Not sure what exactly is causing this. Any guidance is greatly appreciated! (PS. I am new to Kafka so this could totally be an unrelated problem)

**Comment by wzahedi** [comment]
Update: I tried using the default AsyncIterator found at [https://github.com/apollographql/graphql-subscriptions/blob/master/src/pubsub-async-iterator.ts](url)
and it still does not work after a few messages, so the issue is elsewhere i guess.
Any help would be appreciated! Thanks.

**Comment by fmannhardt** [comment]
Could you try the following variant and give your feedback:
https://www.npmjs.com/package/@fmannhardt/graphql-kafka-subscriptions

Here is the related pull request:
https://github.com/ancashoria/graphql-kafka-subscriptions/pull/24

Currently working on getting this into a new version here.

**Comment by rodrigopinto** [comment]
@wzahedi where you able to confirm if it still happening following @fmannhardt suggestions?

**Comment by wzahedi** [comment]
My project no longer requires the use of Kafka for subscriptions unfortunately, so I can't confirm that. I'll close the issue for now.
