### ISSUE TITLE
Only supports for multiple brokers

### ISSUE THREAD

**Issue by cramhead** [ancashoria/graphql-kafka-subscriptions#42]
Would you be willing to accept a PR for adding support for multiple brokers. 
I'm thinking a comma delimited list, as node-rdkafka normally uses

**Comment by smilovanovic** [comment]
@cramhead you should be able to do
```
return new KafkaPubSub({
  port: undefined,
  topic: configService.get('KAFKA_SUBSCRIPTION_TOPIC_NAME'),
  host: configService.get('KAFKA_BROKERS'),
});
```

**Comment by cramhead** [comment]
Thanks, @smilovanovic. Closing this ticket
