### ISSUE TITLE
Passing options through to underlying KafkaConsumer

### ISSUE THREAD

**Issue by ryanlewis** [ancashoria/graphql-kafka-subscriptions#8]
Hi there. Great work on this. 

Have you considered adding the ability to pass options through to the underlying consumer that is created? For example, we are looking to encrypt Kafka topics and would like to configure some of the `ssl.*` properties specified in https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md, but that doesn't look possible yet.

**Comment by ancashoria** [comment]
Hi, this was fixed by this PR https://github.com/ancashoria/graphql-kafka-subscriptions/pull/12
