### ISSUE TITLE
Question: Subscription Durability

### ISSUE THREAD

**Issue by serle** [ancashoria/graphql-kafka-subscriptions#9]
One of the main benefits of Kafka is message durability and the ability for the client to specify an offset. If the client goes offline, will they receive the "skipped" messages over the subscription. This could be different per client although they subscribe to the same Topic/Partition. Its fine to have real-time push, but we really need more of a pull/push system.

**Comment by gklijs** [comment]
If you want to be sure every 'end-user' gets every message, you likely to want to use query and/or mutation and not subscription. Using a one to one relation between 'end-users' and Kafka Consumer Groups has a lot of problems. Not only scalability, but by default offsets get erased after some time, if the Group hasn't been online. But also when are you sure the 'end-user' has read the message?

**Comment by rodrigopinto** [comment]
Hi @serle,

> If the client goes offline, will they receive the "skipped" messages over the subscription.

The design of a Pub/Sub system does not guarantee the deliverability of a published messages to the clients(subscribers). If it would be the case it would add unnecessary complexity to design of the lib and make the package behave different from a the [graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions) API and also differ from the PubSub Architecture.

Additionally, in this package the _message bus_, is backed by Kafka, but it could be redis or postgres(that also has durability :) ).

To keep your clients up to date, I would recommend to approach a solution which consider a re/fetching using a Query instead , as also @gklijs already mentioned.
